fruits=['apple','banana','cherry',1,2,3,'apple']
veg=('ghira','lauka')
print(type(fruits))
print(fruits.append('litchi'))#this is not applicable 100%
print(fruits)
print(len(fruits))
print(fruits.extend('raj'))#SAA
print(fruits)
print(fruits.extend(veg))#SAA
print(fruits)
print(fruits.insert(1,"mango"))#SAA
print(fruits)
print(fruits.count('apple'))
print(fruits.index('apple'))
fruits=['apple','banana','cherry',1,2,3,'apple']
print(fruits.remove('apple'))#SAA
print(fruits)
fruits=['apple','banana','cherry',1,2,3,'strawbrry']
print(fruits.pop(1))
print(fruits)
print(fruits.reverse())#SAA
print(fruits)
fruits=['apple','dog','cherry','asttrawbrry']
fruits.sort()#assending
print(fruits)
fruits.sort(reverse=True)#decending
print(fruits)
print('hii')
print(fruits.copy())
